MyProject/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyProject.Models;
using Microsoft.AspNetCore.Mvc;
using MyProject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace MyProject.Controllers
{
    public class NoteController : Controller
    {
        private IRepository repository;

        private UserManager<ApplicationUser> userManager;

        public int PageSize = 5;

        public NoteController(IRepository repo, UserManager<ApplicationUser> usrMgr)
        {
            repository = repo;
            userManager = usrMgr;
        }

        public ViewResult List(int notePage = 1)
        {
            return View(new NoteListViewModel
            {
                Notes = repository.Notes
                  .Include(p => p.ApplicationUser)
                  .OrderByDescending(p => p.Date)
                  .Skip((notePage - 1) * PageSize)
                  .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = notePage,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Notes.Count()
                }
            });
        }

        
        [Authorize]     
        [HttpGet]
        public ViewResult Create()
        {
            return View (new Note());
        }

        [HttpPost]
        public IActionResult Create(Note note)
        {
            if (ModelState.IsValid)
            {
                note.ApplicationUserId = GetCurrentUserId();
                note.Date = DateTime.Now.Date;
                repository.AddNote(note);
                TempData["message"] = $"{note.Name} создан";
                return RedirectToAction("List");
            }
            else
            {
                return View(note);
            }
        }

        [Authorize]
        public ViewResult Edit(int noteId)
        {
            return View(repository.Notes
            .FirstOrDefault(p => p.Id == noteId));
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                repository.SaveNote(note);
                TempData["message"] = $"{note.Name} сохранен";
                return RedirectToAction("List");
            }
            else
            {
                return View(note);
            }
        }

        private string GetCurrentUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
        
        private async Task<bool> CurrentUserIsAdmin()
        {
            var user = await userManager.GetUserAsync(User);
            if (user == null) return false;
            else return await userManager.IsInRoleAsync(user, "admin");
        }

        public async Task<ViewResult> Note(int id)
        {
            
            Note note = repository.Notes
                                  .Include(p => p.Comments)
                                    .ThenInclude(c => c.ApplicationUser)
                                  .Include(p => p.ApplicationUser)
                                  .Single(p => p.Id == id);
            
            ViewBag.IsAuthor = note.ApplicationUserId == GetCurrentUserId() ? true : false;
            if (await CurrentUserIsAdmin()) ViewBag.IsAuthor = true;
            return View(note);
        }
        
        [HttpPost]
        public IActionResult Delete(Note note)
        {
            repository.DeleteNote(note);
            TempData["Message"] = $"Конспект удален";
            return RedirectToAction("List");

        }
    }
}

MyProject/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyProject.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Korzh.EasyQuery.Linq;
using MyProject.Models;
using Microsoft.EntityFrameworkCore;

namespace MyProject.Controllers
{
    public class SearchController : Controller
    {
        private IRepository repository;

        public int PageSize = 5;

        public SearchController(IRepository repo)
        {
            repository = repo;
        }

        public ViewResult SearchList(string text, int notePage = 1)
        {
            IQueryable<Note> notes = repository.Notes;
            if (!string.IsNullOrEmpty(text))
            {
                notes = repository.Notes.FullTextSearchQuery(text);                   
            }
            
            return View(new NoteListViewModel
            {
                Notes = notes
                    .Include(p => p.ApplicationUser)
                    .OrderByDescending(p => p.Date)
                    .Skip((notePage - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = notePage,
                    ItemsPerPage = PageSize,
                    TotalItems = notes.Count()
                }
            });
         
        }

       /* private IQueryable<Note> SearchNotes(string text)
        {
            IQueryable<Note> notes;
            if (!string.IsNullOrEmpty(text))
            {
                notes = repository.Notes.FullTextSearchQuery(text);
            }
            else
            {
                notes = repository.Notes;
            }
        }

        private IQueryable<Comment> SearchComment(string text)
        {

        }*/
    }
}

MyProject/Views/Shared/_AdminPartial.cshtml
@model ApplicationUser
<div class="card" id="@Model.Id">
    <div class="card-body">
        <div class="d-flex bd-highlight mb-3">
            <div class="mr-auto p-2 bd-highlight">
                <a asp-controller="Account" asp-action="UserAccount" asp-route-id="@Model.Id">@Model.UserName</a>
                @Model.Email
            </div>
            <div class="d-flex justify-content-end">
                @if (Model.UserIsLocked)
                {<a class="status btn btn-xs btn-success" data-id="@Model.Id">Разблокировать</a> }
                else
                { <a class="status btn btn-xs btn-warning" data-id="@Model.Id">Заблокировать</a>}
                <a class="delete btn btn-xs btn-danger" data-id="@Model.Id">Удалить</a>

                <a class="removefromadmin btn btn-light" data-id="@Model.Id">Снять должность администратора</a>
            </div>
        </div>
    </div>
</div>  

MyProject/Views/Shared/_CommentPartial.cshtml
@model Comment
<div class="card" id="@Model.Id" style="min-height: 100px">
    <div class="d-flex bd-highlight">
        <div class="p-2 bd-highlight">
            <img class="d-flex mr-3 rounded-circle" style="max-height: 50px" src="@Model.ApplicationUser.Image" alt="">
        </div>
        <div class="p-2 flex-grow-1 bd-highlight">

            <h5 class="mt-0"><a asp-controller="Account" asp-action="UserAccount" asp-route-id="@Model.ApplicationUserId">@Model.ApplicationUser.UserName</a></h5>

            <p>@Model.Text</p>
        </div>
        <div class="p-2 bd-highlight">
            @if ((ViewBag.IsAuthor!=null)&&(ViewBag.IsAuthor))
            {
                <a class="deletecomment" data-id="@Model.Id" style="float: right"><img src="https://ucarecdn.com/2f3b2eb7-109a-47c8-bb46-8c8e5ca9e1cf/delete.png" /></a>
            }
            <div class="like" data-id="@Model.Id"><span class="counter"></span></div>
        </div>
    </div>
</div>
  

MyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyProject</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <!--  <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css" />-->
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        UPLOADCARE_PUBLIC_KEY = '74dd696e2d6100c7e3ff';
        UPLOADCARE_LOCALE = 'ru';
        UPLOADCARE_TABS = 'file camera url facebook gdrive dropbox instagram skydrive vk';
        UPLOADCARE_EFFECTS = 'crop';
        UPLOADCARE_IMAGES_ONLY = true;
    </script>

    <script src="https://ucarecdn.com/libs/widget/3.6.1/uploadcare.full.min.js"></script>
    <script src="https://ucarecdn.com/libs/widget-tab-effects/1.x/uploadcare.tab-effects.js"></script>
    <script>
        uploadcare.registerTab('preview', uploadcareTabEffects)
    </script>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
            <a class="navbar-brand" asp-action="List" asp-controller="Note">Конспекты</a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarCollapse" style="">               
                <form class="form-inline mx-auto" asp-area="" asp-controller="Search" asp-action="SearchList" method="post">
                    <input id="searchtext" name="text" class="form-control mr-sm-2" type="text" placeholder="Найти.." aria-label="Search">
                    <button id="searchbutton" class="btn btn-outline-success my-2 my-sm-0">Найти</button>
                </form>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top: 75px">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
        <hr />

    </div>
    <a class="addnote btn btn-outline-success" asp-action="Create" asp-controller="Note"><img src="https://ucarecdn.com/7546e73b-feb0-4563-8dda-1d3da4a0ff0c/add.png" /></a>
    <footer></footer>

    @RenderSection("Scripts", required: false)

</body>
</html>

MyProject/Views/Shared/_MessagePartial.cshtml
@model string
<div class="alert alert-info">@Model</div>

MyProject/Views/Shared/_NotePartial.cshtml
@model Note
<div class="card mb-4">
   
    <div class="card-body">
        <h2 class="card-title">@Model.Name</h2>
        <p class="card-text">@Model.Description</p>
        <a asp-controller="Note" asp-action="Note" asp-route-id="@Model.Id" class="btn btn-primary">Читать</a>
    </div>
    <div class="card-footer text-muted">
        Добавлено @Model.Date.ToShortDateString() пользователем
        <a asp-controller="Account" asp-action="UserAccount"  asp-route-id="@Model.ApplicationUserId">@Model.ApplicationUser.UserName</a>
    </div>
</div>

MyProject/Views/Shared/_UserPartial.cshtml
@model ApplicationUser
<div class="card" id="@Model.Id">
    <div class="card-body">
        <div class="d-flex bd-highlight mb-3">
            <div class="mr-auto p-2 bd-highlight">
                <a asp-controller="Account" asp-action="UserAccount" asp-route-id="@Model.Id">@Model.UserName</a>
                @Model.Email
            </div>            
            <div class="d-flex justify-content-end">
                @if (Model.UserIsLocked)
                {<a class="status btn btn-xs btn-success" data-id="@Model.Id">Разблокировать</a> }
                else
                { <a class="status btn btn-xs btn-warning" data-id="@Model.Id">Заблокировать</a>}
                <a class="delete btn btn-xs btn-danger" data-id="@Model.Id">Удалить</a>

                <a class="makeadmin btn btn-light" data-id="@Model.Id">Назначить администратором</a>
            </div>
        </div>
    </div>
</div>       