MyProject/Models/AccountViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyProject.Models.AccountViewModels
{
    public class EditViewModel
    { 
        public string Id { get; set; }

        public string Username { get; set; }

        public string AboutUser { get; set; }

        public string Image { get; set; }
    }
}

MyProject/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace MyProject.Models
{
    public class Note
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите название конспекта")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Пожалуйста, добавьте описание конспекта")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Пожалуйста, добавьте содержание конспекта")]
        public string Text { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите номер специальности")]
        [Range(1, 12, ErrorMessage = "Неверный номер специальности")]
        public string NumberSpecialty { get; set; }

        public DateTime Date { get; set; }

        public string Image { get; set; }

        public string ApplicationUserId { get; set; }

        public ApplicationUser ApplicationUser { get; set; }

        public List<Comment> Comments { get; set; }

    }
}

MyProject/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MyProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MyProject.Controllers
{
    public class CommentController : Controller
    {
        private IRepository repository;

        private UserManager<ApplicationUser> userManager;

        public CommentController(IRepository repo, UserManager<ApplicationUser> usrMgr)
        {
            repository = repo;
            userManager = usrMgr;
        }

        public string GetCurrentUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }

        [HttpPost]
        public async Task<ActionResult> AddComment(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.ApplicationUser = await userManager.FindByIdAsync(GetCurrentUserId());
                repository.AddComment(comment);
                return PartialView("_CommentPartial", comment);
            }
            else return PartialView("_MessagePartial", "Введите текст комментария");
            
        }

        [HttpPost]
        public bool DidLike(int commentId)
        {
            if (FoundLike(commentId) == null) { return false; }
            else { return true; }
        }

        [HttpPost]
        public int LikeCount(int commentId)
        {
            return repository.Likes.Where(p => p.CommentId == commentId).Count();
        }

        [HttpPost]
        public bool ChangeLike(int commentId)
        {
            Like like = FoundLike(commentId);
            if (like == null)
            {
                repository.AddLike(new Like { ApplicationUserId = GetCurrentUserId(), CommentId = commentId });
                return true;
            }
            else
            {
                repository.DeleteLike(like);
                return false;
            }
        }

        private Like FoundLike(int commentId)
        {
            var usersLikes = repository.Likes.Where(p => p.ApplicationUserId == GetCurrentUserId());
            return usersLikes.FirstOrDefault(p => p.CommentId == commentId);
        }

        [HttpPost]
        public IActionResult Delete(int commentId)
        {
            repository.DeleteComment(commentId);
            return PartialView("_MessagePartial", "Комментарий удален");
        }
    }
}

MyProject/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyProject.Models;
using Microsoft.AspNetCore.Mvc;
using MyProject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace MyProject.Controllers
{
    public class NoteController : Controller
    {
        private IRepository repository;

        private UserManager<ApplicationUser> userManager;

        public int PageSize = 5;

        public NoteController(IRepository repo, UserManager<ApplicationUser> usrMgr)
        {
            repository = repo;
            userManager = usrMgr;
        }

        public ViewResult List(int notePage = 1)
        {
            return View(new NoteListViewModel
            {
                Notes = repository.Notes
                  .Include(p => p.ApplicationUser)
                  .OrderByDescending(p => p.Date)
                  .Skip((notePage - 1) * PageSize)
                  .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = notePage,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Notes.Count()
                }
            });
        }

        
        [Authorize]     
        [HttpGet]
        public ViewResult Create()
        {
            return View (new Note());
        }

        [HttpPost]
        public IActionResult Create(Note note)
        {
            if (ModelState.IsValid)
            {
                note.ApplicationUserId = GetCurrentUserId();
                note.Date = DateTime.Now.Date;
                repository.AddNote(note);
                TempData["message"] = $"{note.Name} создан";
                return RedirectToAction("List");
            }
            else
            {
                return View(note);
            }
        }

        [Authorize]
        public ViewResult Edit(int noteId)
        {
            return View(repository.Notes
            .FirstOrDefault(p => p.Id == noteId));
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                repository.SaveNote(note);
                TempData["message"] = $"{note.Name} сохранен";
                return RedirectToAction("List");
            }
            else
            {
                return View(note);
            }
        }

        private string GetCurrentUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
        
        private async Task<bool> CurrentUserIsAdmin()
        {
            var user = await userManager.GetUserAsync(User);
            if (user == null) return false;
            else return await userManager.IsInRoleAsync(user, "admin");
        }

        public async Task<ViewResult> Note(int id)
        {
            
            Note note = repository.Notes
                                  .Include(p => p.Comments)
                                    .ThenInclude(c => c.ApplicationUser)
                                  .Include(p => p.ApplicationUser)
                                  .Single(p => p.Id == id);
            
            ViewBag.IsAuthor = note.ApplicationUserId == GetCurrentUserId() ? true : false;
            if (await CurrentUserIsAdmin()) ViewBag.IsAuthor = true;
            return View(note);
        }
        
        [HttpPost]
        public IActionResult Delete(Note note)
        {
            repository.DeleteNote(note);
            TempData["Message"] = $"Конспект удален";
            return RedirectToAction("List");

        }
    }
}

MyProject/Views/Note/Create.cshtml
@model Note
@{
    ViewBag.Title = "Новый конспект";
}


<form asp-action="Create" method="post">
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="Name">Название</label>
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Name" type="text" placeholder="Название" class="form-control" />
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="Description">Краткое описание</label>
            <div><span asp-validation-for="Description" class="text-danger"></span></div>
            <textarea rows="3" asp-for="Description" placeholder="Краткое описание" class="form-control"></textarea>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="Text">Содержание</label>
            <div><span asp-validation-for="Text" class="text-danger"></span></div>
            <textarea rows="6" asp-for="Text" placeholder="Содержание" class="form-control"></textarea>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="NumberSpecialty">Номер специальности</label>
            <div><span asp-validation-for="NumberSpecialty" class="text-danger"></span></div>
            <input asp-for="NumberSpecialty" type="number" placeholder="Номер специальности" class="form-control" />
        </div>
    </div>
    <input asp-for="Image" value="" type="hidden"
           role="uploadcare-uploader"
           name="Image"
           data-crop="free"
           class="btn btn-dark" />

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Сохранить</button>
        <a asp-action="List" class="btn btn-secondary">Отмена</a>
    </div>
</form>
<script>
    var widget = uploadcare.SingleWidget('[role=uploadcare-uploader]');
    widget.onChange(function (file) {
        if (file) {
            file.done(function (info) {
                widget.val = info.cdnUrl;
            });
        };
    });
</script>

MyProject/Views/Note/Edit.cshtml
@model Note
@{
    ViewBag.Title = "Редактирование";
}


<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ApplicationUserId" />
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="Name">Название</label>
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Name" type="text" placeholder="Название" class="form-control" />
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="Description">Краткое описание</label>
            <div><span asp-validation-for="Description" class="text-danger"></span></div>
            <textarea rows="3" asp-for="Description" placeholder="Краткое описание" class="form-control"></textarea>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="Text">Содержание</label>
            <div><span asp-validation-for="Text" class="text-danger"></span></div>
            <textarea rows="6" asp-for="Text" placeholder="Содержание" class="form-control"></textarea>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label asp-for="NumberSpecialty">Номер специальности</label>
            <div><span asp-validation-for="NumberSpecialty" class="text-danger"></span></div>
            <input asp-for="NumberSpecialty" type="number" min="1" max="12" placeholder="Номер специальности" class="form-control" />
        </div>
    </div>
    <input asp-for="Image" value="" type="hidden"
           role="uploadcare-uploader"
           name="Image"
           data-crop="free"
           class="btn btn-dark" />

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Сохранить</button>
        <a asp-action="List" class="btn btn-secondary">Отмена</a>
    </div>
</form>
<script>
    var widget = uploadcare.SingleWidget('[role=uploadcare-uploader]');
    widget.onChange(function (file) {
        if (file) {
            file.done(function (info) {
                widget.val = info.cdnUrl;
            });
        };
    });
</script>

MyProject/Views/Note/Kek.cshtml
@model string
<h2>@Model</h2>

MyProject/Views/Note/List.cshtml
@model NoteListViewModel

<div class="row">
    
    <div class="col-md-8 mx-auto">
        @foreach (var n in Model.Notes)
        {
            @Html.Partial("_NotePartial", n)
        }
        <div page-model="@Model.PagingInfo" page-action="List" page-classes-enabled="true"
             page-class="btn" page-class-normal="btn-secondary"
             page-class-selected="btn-primary" class="btn-group pull-right m-1">
        </div>
    </div>

</div>

MyProject/Views/Note/Note.cshtml
@inject SignInManager<ApplicationUser> SignInManager

@model Note

<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1 class="mt-4">@Model.Name</h1>
        <p class="lead">
            Автор:
            <a asp-controller="Account" asp-action="UserAccount" asp-route-id="@Model.ApplicationUserId">@Model.ApplicationUser.UserName</a>
        </p>
        <hr>
        <p>Добавлено @Model.Date.ToShortDateString()</p>
        
        <img class="img-fluid rounded" src="@Model.Image" alt="">
        <hr>
        @if ((ViewBag.IsAuthor != null) && (ViewBag.IsAuthor))
        {
            <div>
                <a class="btn btn-outline-success" asp-controller="Note" asp-action="Edit" asp-route-noteId="@Model.Id">Редактировать</a>
                <form asp-controller="Note" asp-action="Delete" method="post" style="float:right">
                    <input asp-for="Id" type="hidden"/>
                    <button class="btn btn-danger" type="submit">Удалить</button>
                </form>
            
            </div>
        }
        <p class="lead">@Model.Description</p>
        <p>@Model.Text</p>
        <hr>
        
        @if (SignInManager.IsSignedIn(User))
        {
            <div id="commentsDiv">
                @foreach (var c in Model.Comments)
                {
                    @Html.Partial("_CommentPartial", c)
                }
            </div>
            <div class="card my-4">
                <h5 class="card-header">Оставить комментарий:</h5>
                <div class="card-body">
                    <form asp-action="AddComment" method="post">
                        <div class="form-group">
                            <textarea id="textComment" class="form-control" rows="3" placeholder="Добавить комментарий..."></textarea>
                        </div>
                        <input type="hidden" asp-for="@Model.Id" id="noteId" value="@Model.Id" />
                    </form>
                    <button class="btn btn-primary" id="addcommentbutton">Добавить</button>
                </div>
            </div>
        }
    </div>
</div>

<script>
    $(document).ready(function () {
        $(".like").each(function () {
            var link = $(this);
            var id = link.data("id");
            $.ajax({
                url: '@Url.Action("LikeCount", "Comment")',
                type: "POST",
                async: true,
                data: {
                    commentId: id
                },
                success: function (result) {
                    if (result) {
                        $('.counter', link).html(result);
                    }
                    else {
                        $('.counter', link).html(0);
                    }
                }
            });
            $.ajax({
                url: '@Url.Action("DidLike", "Comment")',
                type: "POST",
                async: true,
                data: {
                    commentId: id
                },
                success: function (result) {
                    if (result) {
                        link.addClass('active');
                    }
                }
            });
        });
    });

    $(function () {
        function LikeCount(id,link) {
            $.ajax({
                url: '@Url.Action("LikeCount", "Comment")',
                type: "POST",
                async: true,
                data: {
                    commentId: id
                },
                success: function (result) {
                    if (result) {
                        $('.counter', link).html(result);
                    }
                    else {
                        $('.counter', link).html(0);
                    }
                }
            });
        }
        $("#addcommentbutton").on('click', function () {
            $.ajax({
                url: '@Url.Action("AddComment","Comment")',
                type: 'POST',
                async: true,
                data: {
                    comment: {
                        NoteId: $("#noteId").val(),
                        Text: $("#textComment").val()
                    }
                },
                success: function (data) {
                    if (data) {
                        $("#commentsDiv").append(data);
                    }
                    $("#textComment").val("");
                }
            })
        })
        $("#commentsDiv").on('click','.like',function () {
            var link = $(this);
            var id = link.data("id");
            $.ajax({
                url: '@Url.Action("ChangeLike", "Comment")',
                type: "POST",
                async: true,
                data: {
                    commentId: id
                },
                success: function (result) {
                    if (result) {
                        link.addClass('active');
                    }
                    else {
                        link.removeClass('active');
                    }
                    LikeCount(id,link);
                },               
            });
            
        });
        $("#commentsDiv").on('click','.deletecomment',function () {
            var link = $(this);
            var id = link.data("id");
            $.ajax({
                url: '@Url.Action("Delete", "Comment")',
                type: "POST",
                async: true,
                data: {
                    commentId: id
                },
                success: function (data) {
                    var elem = document.getElementById(id);
                    $(elem).replaceWith(data);
                },               
            });
            
        });
    });

</script>